// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"boilerplate/internal/apps"
	"boilerplate/internal/modules/directory"
	"boilerplate/internal/modules/meta"
)

// Injectors from wire.go:

func InitializeSampleApp(m *meta.Meta) *apps.SampleApp {
	handler := meta.NewHandler(m)
	directoryHandler := directory.NewHandler()
	sampleApp := apps.NewSampleApp(handler, directoryHandler)
	return sampleApp
}
