// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Init(arg1) {
  return window['go']['directory']['handler']['Init'](arg1);
}

export function SelectDirectory() {
  return window['go']['directory']['handler']['SelectDirectory']();
}
