// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppMeta() {
  return window['go']['meta']['handler']['GetAppMeta']();
}

export function Init(arg1) {
  return window['go']['meta']['handler']['Init'](arg1);
}
