// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {meta} from '../models';
import {context} from '../models';

export function GetAppMeta():Promise<meta.Meta>;

export function Init(arg1:context.Context):Promise<void>;
